### ISSUE TITLE
default --separator is incompatible with 'aws configure'

### ISSUE THREAD

**Issue by briceburg** [benkehoe/aws-sso-util#90]
It may be too late to change this due to backwards compatibility, but I wanted report that the default dot (.) separator is incompatible with 'aws configure', and suggest changing it to a plus (+) instead.

Example:

```sh
# profile = "foo+write"
aws configure set "profile.foo+write.role_arn" "arn:aws:iam::1234567:role/ci_write"
```

if the profile has a dot in it, it fails miserably...
```sh
# profile = "foo.write"
aws configure set "profile.foo\.write.role_arn" "arn:aws:iam::1234567:role/ci_write"
``` 

^^^ results in multiple lines in `~/.aws/config` (no matter the escaping attempts)

**Comment by benkehoe** [comment]
Interesting. I'd suggest opening a bug on the AWS CLI for this as well.

As for the use case, what exactly are you trying to modify on these auto-generated profiles?

**Comment by briceburg** [comment]
@benkehoe yes, if we were able to figure out how to escape the dot in the aws cli all would be good! so certainly worth a report there...

re: our particular use case; we're programmatically creating profiles on CI/CD machines according to the profile naming conventions that `aws-sso-util configure populate` produces on developer machines. so not actually modifying auto-generated profiles, but if we were the `aws configure set` command is an option =)

**Comment by benkehoe** [comment]
I'm skeptical that's a good idea. I tend to recommend against enforcing profile naming conventions across users and especially across users and machines (where one is using SSO roles and the other plain IAM roles but with the same profile names). One good example of why is if it requires you tell everyone they have to use `--separator +` or it will break 🙂

But given that approach I'd say instead of a bunch of `aws configure set` commands modifying the default config file, you might consider prebuilding a config file offline, bundling it in the CI/CD image, and then using the `AWS_CONFIG_FILE` environment variable to point at that file.

**Comment by briceburg** [comment]
✅ great idea re: pre-baking the AWS_CONFIG_FILE. we're not yet using images (everything is executing in the default github action  runner), but can workaround the need to execute `aws configure` to populate things... I just wanted to bring up a use-case where the '.' separator could prove problematic.

also agree re: profile naming conventions, it's definitely a fragile road and has continually proven so! most of our workflows come from terraform conventions where we've inherited named profiles to identify target accounts...

**Comment by benkehoe** [comment]
> I just wanted to bring up a use-case where the '.' separator could prove problematic.

It's good bit of info to know!

For GitHub Actions, if you're not putting the config file in the repo, I'd think step or custom action using a heredoc to write it is probably the right answer. Something like
```yaml
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::123456789100:role/my-github-actions-role
          aws-region: us-east-2
      - name: Set up config file
        run: |
          cat << EOF > awsconfig.ini
          [profile foo.write]
          role_arn = arn:aws:iam::1234567:role/ci_write
          credential_source = Environment
          EOF
      - run: aws sts get-caller-identity --profile foo.write
        env:
          AWS_CONFIG_FILE: awsconfig.ini
```
